[project]
name = "mlops"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "memray>=1.17.2",
    "mypy>=1.15.0",
    "ruff>=0.11.11",
]

[tool.uv.workspace]
members = [
    "basic/01_avg",
]
