[project]
name = "pytorch-demo"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flytekit>=1.16.4",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]
